### ISSUE TITLE
v.1.08.12_patch01 denoise hyb error

### ISSUE THREAD

**Issue by ginpigin** [km2ii/JP109A_TG-PLUS#10]
denoise almost works, now hyb throws an error [info] Denoising please wait....
Script evaluation failed:
Python exception: No module named 'muvsfunc'

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 1946, in vapoursynth.vpy_evaluateScript
File "src\cython\vapoursynth.pyx", line 1947, in vapoursynth.vpy_evaluateScript
File "Vapoursynth\hyb.vpy", line 7, in
ModuleNotFoundError: No module named 'muvsfunc'

Script evaluation failed:
Python exception: No module named 'muvsfunc'

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 1946, in vapoursynth.vpy_evaluateScript
File "src\cython\vapoursynth.pyx", line 1947, in vapoursynth.vpy_evaluateScript
File "Vapoursynth\hyb.vpy", line 7, in
ModuleNotFoundError: No module named 'muvsfunc'

Script evaluation failed:
Python exception: No module named 'muvsfunc'

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 1946, in vapoursynth.vpy_evaluateScript
File "src\cython\vapoursynth.pyx", line 1947, in vapoursynth.vpy_evaluateScript
File "Vapoursynth\hyb.vpy", line 7, in
ModuleNotFoundError: No module named 'muvsfunc'

**Comment by km2ii** [comment]
[https://github.com/WolframRhodium/muvsfunc/blob/master/muvsfunc.py](url)

**Comment by ginpigin** [comment]
nice, it's works now. thanks
