### ISSUE TITLE
v1.08.12  Denoising don't work

### ISSUE THREAD

**Issue by ginpigin** [km2ii/JP109A_TG-PLUS#9]
v1.08.12 [info] Denoising please wait ....
"vspipe.exe" is not internal or external
command, executable program, or batch file.
"vspipe.exe" is not internal or external
command, executable program, or batch file.
"vspipe.exe" is not internal or external
command, executable program, or batch file.

**Comment by AdamMacchiato** [comment]
may be you have to set the Pythonhome and Pythonpath , located to x:\xxx\TG\TGMAIN\Vapoursynth

**Comment by km2ii** [comment]
Fix vspipe.exe path error.
https://workupload.com/file/CtShEwPrmnt

**Comment by ginpigin** [comment]
denoise almost works, now hyb throws an error [info] Denoising please wait....
Script evaluation failed:
Python exception: No module named 'muvsfunc'

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 1946, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 1947, in vapoursynth.vpy_evaluateScript
  File "Vapoursynth\hyb.vpy", line 7, in <module>
ModuleNotFoundError: No module named 'muvsfunc'

Script evaluation failed:
Python exception: No module named 'muvsfunc'

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 1946, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 1947, in vapoursynth.vpy_evaluateScript
  File "Vapoursynth\hyb.vpy", line 7, in <module>
ModuleNotFoundError: No module named 'muvsfunc'

Script evaluation failed:
Python exception: No module named 'muvsfunc'

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 1946, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 1947, in vapoursynth.vpy_evaluateScript
  File "Vapoursynth\hyb.vpy", line 7, in <module>
ModuleNotFoundError: No module named 'muvsfunc'
